// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewMeetup struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	UserID      string `json:"userId"`
}

type NewUser struct {
	Username string `json:"username"`
	Email    string `json:"email"`
}
